### ISSUE TITLE
Out of Order Class Elaboration Broken

### ISSUE THREAD

**Issue by sdgoodrick** [lock3/cppx#16]
I disabled tests in `GoldClassParsing.cpp` and `GoldUnionElab.cpp` because out-of-order class elaboration seems to have been broken by the recent refactoring.

This is a low-priority issue.

**Comment by bbartman** [comment]
I finally found this, and figured out what was happening.

I was missing a member variable initialization from the constructor parameters. Once I get everything merged with master and I have everything working again, I'll close this and uncomment the broken tests.
