### ISSUE TITLE
Late Elaborated Methods are all Inline

### ISSUE THREAD

**Issue by sdgoodrick** [lock3/cppx#85]
in `GoldElaborator.cpp::lateElaborateMethodDef()`
```
  SemaRef.getCxxSema().ActOnFinishInlineFunctionDef(
    cast<clang::FunctionDecl>(Method.D->Cxx));
```

Assuming any late-elaborated method is inline is an invalid assumption: all inline functions must have a body, and we can have
```
Typename[T : type] : type = class:
  destructor() = default
```
The destructor does not have a body.

See also: https://github.com/lock3/cppx/issues/72

**Comment by sdgoodrick** [comment]
I added a case for functions with no body to bypass the inline function finalization. Waiting for comment from @bbartman before closing

**Comment by bbartman** [comment]
That seems fine so long as we have a test for it.
